import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { AGENT_OPERATION } from '../../packages/web/server/lib/agent/constants.js';
import { AGENT_INPUT_SCHEMAS, AGENT_OUTPUT_SCHEMAS } from '../../packages/web/server/lib/agent/schemas.js';
import { OPERATION_REFERENCE } from './operation-reference.mjs';
import { buildContractPages, CONTRACT_REFERENCE } from './contract-pages.mjs';
import { runContractCommand } from './build-contracts.mjs';

test('every operation has bilingual semantics and parser-checked positive and negative fixtures', () => {
  assert.deepEqual(Object.keys(OPERATION_REFERENCE).sort(), Object.values(AGENT_OPERATION).sort());
  const { files } = buildContractPages();
  assert.equal(files.size, 69);
  for (const operation of Object.values(AGENT_OPERATION)) {
    const reference = JSON.parse(files.get(`${CONTRACT_REFERENCE.EN}/schemas/${operation}.json`));
    assert.equal(reference.operation, operation);
    assert.equal(AGENT_INPUT_SCHEMAS[operation].safeParse(reference.examples.input).success, true);
    assert.equal(AGENT_OUTPUT_SCHEMAS[operation].safeParse(reference.examples.output).success, true);
    assert.equal(AGENT_OUTPUT_SCHEMAS[operation].safeParse(reference.examples.invalidOutput).success, false);
    for (const root of [CONTRACT_REFERENCE.EN, CONTRACT_REFERENCE.ZH]) {
      assert.ok(files.get(`${root}/${operation}.md`).includes(`\`\`\`json\n`));
      assert.ok(files.get(`${root}/README.md`).includes(`(${operation}.md)`));
    }
  }
});

test('reference digest is deterministic and covers the exact generated bytes', () => {
  const first = buildContractPages();
  const second = buildContractPages();
  assert.deepEqual([...first.files], [...second.files]);
  const manifest = JSON.parse(first.files.get(CONTRACT_REFERENCE.MANIFEST));
  assert.equal(manifest.operations.length, 22);
  assert.equal(manifest.files.length, 68);
  assert.equal(new Set(manifest.files.map((entry) => entry.path)).size, 68);
  for (const entry of manifest.files) {
    assert.equal(createHash('sha256').update(first.files.get(entry.path)).digest('hex'), entry.sha256);
  }
  assert.equal(createHash('sha256').update(JSON.stringify(manifest.files)).digest('hex'), manifest.digest);
  assert.equal(manifest.digest, first.digest);
});

test('synthetic child and import examples preserve the documented ownership', () => {
  const children = OPERATION_REFERENCE[AGENT_OPERATION.LIST_CHILDREN];
  assert.notEqual(children.output.items[0].id, children.input.sessionID);
  assert.equal(children.output.items[0].parentID, children.input.sessionID);
  const imported = OPERATION_REFERENCE[AGENT_OPERATION.IMPORT_SESSION].input;
  assert.equal(imported.session.workspaceID, imported.workspaceID);
  assert.ok(imported.messages.every((message) => message.sessionID === imported.session.id));
});

test('missing, changed and regenerated references have nonzero or zero checks without activation', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'cagent-reference-'));
  const lines = [];
  const invoke = (args) => runContractCommand(args, root, (line) => lines.push(line));
  try {
    assert.equal(await invoke(['--check', '--json']), 1);
    assert.equal(JSON.parse(lines.pop()).mismatches, 69);
    assert.equal(await invoke(['--write', '--json']), 0);
    assert.equal(JSON.parse(lines.pop()).files, 69);
    assert.equal(await invoke(['--json']), 0);
    assert.equal(JSON.parse(lines.pop()).mode, 'check');
    const changed = path.join(root, CONTRACT_REFERENCE.ZH, `${AGENT_OPERATION.SEND_PROMPT}.md`);
    await fs.appendFile(changed, '\nChanged fixture text\n');
    assert.equal(await invoke(['--check', '--json']), 1);
    const failed = JSON.parse(lines.pop());
    assert.equal(failed.mismatches, 1);
    assert.equal(failed.error, 'reference-stale');
    assert.equal(await invoke(['--write', '--quiet']), 0);
    assert.match(lines.pop(), /^write passed files:69 mismatches:0 digest:[a-f0-9]{64}$/);
    assert.equal(await invoke(['--check']), 0);
    assert.match(lines.pop(), /^check passed files:69/);
    const extra = path.join(root, CONTRACT_REFERENCE.EN, 'removed-operation.md');
    await fs.writeFile(extra, 'Obsolete contract');
    assert.equal(await invoke(['--check', '--json']), 1);
    assert.equal(JSON.parse(lines.pop()).mismatches, 1);
    assert.equal(await invoke(['--write', '--json']), 1);
    assert.equal(JSON.parse(lines.pop()).mismatches, 1);
    assert.equal(await fs.readFile(extra, 'utf8'), 'Obsolete contract');
    assert.equal((await fs.readdir(root)).join(','), 'docs');
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});

test('invalid flags fail in JSON and human modes before writing', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'cagent-reference-'));
  try {
    for (const args of [['--unknown'], ['--write', '--check'], ['unexpected-positional']]) {
      const human = [];
      const machine = [];
      assert.equal(await runContractCommand(args, root, (line) => human.push(line)), 1);
      assert.equal(await runContractCommand([...args, '--json'], root, (line) => machine.push(line)), 1);
      assert.equal(human.length, 1);
      assert.equal(machine.length, 1);
      assert.equal(JSON.parse(machine[0]).ok, false);
      assert.deepEqual(await fs.readdir(root), []);
    }
  } finally {
    await fs.rm(root, { recursive: true, force: true });
  }
});

test('native piped command returns one JSON failure without a prompt or raw exception', () => {
  const script = fileURLToPath(new URL('./build-contracts.mjs', import.meta.url));
  const result = spawnSync(process.execPath, [script, '--unknown', '--json'], { encoding: 'utf8', timeout: 10000 });
  assert.equal(result.error, undefined);
  assert.equal(result.status, 1);
  assert.equal(result.stderr, '');
  assert.equal(JSON.parse(result.stdout).ok, false);
  assert.equal(result.stdout.trim().split('\n').length, 1);
});
